image: alpine/latest
packages:
  - bash
  - icu-libs
  - krb5-libs
  - libgcc
  - libintl
  - libssl1.1
  - libssl1.1
  - zlib
sources:
  - https://git.ivar.systems/IOL.VippsEcommerce
tasks:
  - install-dotnet: |
      wget https://dot.net/v1/dotnet-install.sh
      chmod +x dotnet-install.sh
      bash dotnet-install.sh -c 5.0
  - display-dotnet-info: |
      $HOME/.dotnet/dotnet --info
  - restore: |
      cd $HOME/IOL.VippsEcommerce
      $HOME/.dotnet/dotnet restore src/IOL.VippsEcommerce.Tests/IOL.VippsEcommerce.Tests.csproj
  - build: |
      cd $HOME/IOL.VippsEcommerce
      $HOME/.dotnet/dotnet build --no-restore src/IOL.VippsEcommerce.Tests/IOL.VippsEcommerce.Tests.csproj
  - test: |
      cd $HOME/IOL.VippsEcommerce
      $HOME/.dotnet/dotnet test --no-build --verbosity normal src/IOL.VippsEcommerce.Tests/IOL.VippsEcommerce.Tests.csproj
