image: alpine/latest
packages:
  - dotnet
sources:
  - https://git.sr.ht/~ivar/IOL.VippsEcommerce
tasks:
  - restore: |
      dotnet restore src/IOL.VippsEcommerce.Tests/IOL.VippsEcommerce.Tests.csproj
  - build: |
      dotnet build --no-restore src/IOL.VippsEcommerce.Tests/IOL.VippsEcommerce.Tests.csproj
  - test: |
      dotnet test --no-build --verbosity normal src/IOL.VippsEcommerce.Tests/IOL.VippsEcommerce.Tests.csproj
