name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Go to tests folder
      run: cd src/IOL.VippsEcommerce.Tests
    - name: pwd
      run: pwd
    - name: Restore dependencies
      run: dotnet restore IOL.VippsEcommerce.Tests.csproj
    - name: Build
      run: dotnet build --no-restore IOL.VippsEcommerce.Tests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal IOL.VippsEcommerce.Tests.csproj
